=== mebigfatguy/pixelle/src/com/mebigfatguy/pixelle/resources/algorithms.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	        targetNamespace="http://pixelle.mebigfatguy.com/0.1.0"
	        xmlns="http://pixelle.mebigfatguy.com/0.1.0"
            elementFormDefault="qualified">
    <xsd:complexType name="AlgorithmsClass">
    	<xsd:sequence>
    		<xsd:element maxOccurs="2" minOccurs="2" name="type" type="TypeClass"/>
    	</xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TypeClass">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="1" name="group" type="GroupClass"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="TypeNameClass" use="required"/>
    </xsd:complexType>
    <xsd:simpleType name="TypeNameClass">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="RGB"/>
    		<xsd:enumeration value="Grayscale"/>
    	</xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="GroupClass">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="algorithm" type="AlgorithmClass"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="AlgorithmClass">
        <xsd:sequence>
            <xsd:element maxOccurs="5" minOccurs="2" name="component" type="ComponentClass"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="ComponentClass">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="NameClass" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:simpleType name="NameClass">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="transparency"/>
            <xsd:enumeration value="red"/>
            <xsd:enumeration value="blue"/>
            <xsd:enumeration value="selection"/>
            <xsd:enumeration value="green"/>
            <xsd:enumeration value="black"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="algorithms" type="AlgorithmsClass"/>
</xsd:schema>

=== mebigfatguy/pixelle/src/com/mebigfatguy/pixelle/resources/algorithms.xml
<!--
/*
 * pixelle - Graphics algorithmic editor
 * Copyright (C) 2008 Dave Brosius
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
-->
<algorithms xmlns="http://pixelle.mebigfatguy.com/0.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="/com/mebigfatguy/pixelle/resources/algorithms.xsd">
    <type name="RGB">
    	<group name="Blends">
    		<algorithm name="linear">
    			<component name="red">
    				(x * 255) / width
    			</component>
    			<component name="green">
    				(y * 255) / height
    			</component>
    			<component name="blue">
    				((width - x) * 255) / width
    			</component>
    			<component name="transparency">
					255
				</component>
				<component name="selection">
					0
				</component>
    		</algorithm>
    	</group>
    </type>
    <type name="Grayscale">
		<group name="Separations">
			<algorithm name="cyan">
				<component name="black">
					(255 - p[x,y].r) - min(min(255 - p[x,y].r, 255 - p[x,y].g), 255 - p[x,y].b)
				</component>
				<component name="selection">
					0
				</component>
			</algorithm>
			<algorithm name="magenta">
				<component name="black">
					(255 - p[x,y].g) - min(min(255 - p[x,y].r, 255 - p[x,y].g), 255 - p[x,y].b)
				</component>
				<component name="selection">
					0
				</component>
			</algorithm>
			<algorithm name="yellow">
				<component name="black">
					(255 - p[x,y].b) - min(min(255 - p[x,y].r, 255 - p[x,y].g), 255 - p[x,y].b)
				</component>
				<component name="selection">
					0
				</component>
			</algorithm>
			<algorithm name="black">
				<component name="black">
					min(min(255 - p[x,y].r, 255 - p[x,y].g), 255 - p[x,y].b)
				</component>
				<component name="selection">
					0
				</component>
			</algorithm>
		</group>
	</type>
</algorithms>
